printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: preserve
jsxSingleQuote: false
trailingComma: none
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
proseWrap: preserve
vueIndentScriptAndStyle: true
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
plugins:
  - "@ianvs/prettier-plugin-sort-imports"

# prettier-plugin-sort-imports
importOrder: ["^@core/(.*)$", "", "^@server/(.*)$", "", "^@ui/(.*)$", "", "^[./]"]
importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"]
importOrderTypeScriptVersion: 5.0.0
